[package]
name = "nox-font"
version = "0.1.0"
edition = "2024"

[dependencies]
nox = { path = "../nox" }
nox-geom = { path = "../nox-geom" }
ttf-parser = "0.25.1"
harfbuzz_rs = "2.0.1"
unicode-segmentation = "1.12.0"
rustc-hash = "2.1.1"
compact_str = { version = "0.9.0" }
