[package]
name = "nox"
version = "0.1.0"
edition = "2024"

[dependencies]
nox-mem = { path = "../nox-mem" }
nox-mem-derive = { path = "../nox-mem-derive" }

ash = "0.38.0"
ash-window = "0.13.0"
raw-window-handle = "0.6.0"
winit = "0.30"
spirv-cross2 = "0.4.3"
shaderc = "0.9.1"
memmap2 = "0.9.5"
fxhash = "0.2.1"
blake3 = "1.8.2"
stb_image = "0.3.0"
