[package]
name = "nox-gui"
version = "0.1.0"
edition = "2024"

[dependencies]
nox = { path = "../nox" }
nox-font = { path = "../nox-font" }
nox-geom = { path = "../nox-geom" }
rustc-hash = { version = "2.1", default-features = false }
compact_str = { version = "0.9.0" }
