[package]
name = "shape-example"
version = "0.1.0"
edition = "2024"

[dependencies]
nox = { path = "../crates/nox" }
nox-geom = { path = "../crates/nox-geom" }
nox-shapes = { path = "../crates/nox-shapes" }
